spring.application.name=pedidos
server.port=${PORT:8082}

spring.datasource.url=${DB_URL:jdbc:mysql://gateway01.us-east-1.prod.aws.tidbcloud.com:4000/criollos?sslMode=REQUIRED&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:3z8rcF6QFicbDAN.root}
spring.datasource.password=${DB_PASSWORD:iAe91Tnvia1zXnw4}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# NUEVO DIALECTO
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=${JWT_SECRET:criollos-auth-secret}
jwt.expiration-seconds=${JWT_EXPIRATION_SECONDS:86400}

criollos.auth.url=http://localhost:8080
criollos.producto.url=http://localhost:8081
