spring.application.name=noti
server.port=${PORT:8083}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pdpm15042002@gmail.com
spring.mail.password=clck fnyn ycsb imow
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=15000
spring.mail.properties.mail.smtp.timeout=15000
spring.mail.properties.mail.smtp.writetimeout=15000

notifications.orders.recipient-email=cmateoramirez@ucundinamarca.edu.co
notifications.orders.from-email=pdpm15042002@gmail.com
