spring.application.name=noti
server.port=${PORT:8083}

spring.mail.host=in-v3.mailjet.com
spring.mail.port=587
spring.mail.username=b268db483ee8fc470209d1ab6aba0484
spring.mail.password=cb8779310db367b2625ef8f3d9c4f4b4
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=15000
spring.mail.properties.mail.smtp.timeout=15000
spring.mail.properties.mail.smtp.writetimeout=15000

notifications.orders.recipient-email=cmateoramirez@ucundinamarca.edu.co
notifications.orders.from-email=pdpm15042002@gmail.com
